### ISSUE TITLE
Trajectory highlights enhancements

### ISSUE THREAD

**Issue by cesartl** [AdityaGupta1/minecraft-catapult#15]
The current highlights is excellent. This gave me ideas for the following enhancements:

1. Colour of the trajectory spark should be the same as the colour of the riding block
2. Trajectory for each launch could stay until cleared with a special command e.g. `/clearTrajectory` (perhaps the clear command could also remove all the cows so we can start a new "experiment" with a clean field)

This would allow the kids to compare the different trajectory and help them understand the impact of angle and initial speed

**Comment by AdityaGupta1** [comment]
Number 1 wouldn't work because the blocks are random each time.

For number 2, I am a bit confused as to what you are asking. Trajectories don't show up when you launch the actual block, only when you shift-click on it (and it launches an invisible block). Do you mean shift-clicking should create a new trajectory if the angle/power has changed, and that the command should clear all existing trajectories?

**Comment by AdityaGupta1** [comment]
I added a feature which I think matches what you are asking. If you were asking something else, please let me know here or create a new issue.

**Comment by cesartl** [comment]
For 1. then I think we should remove the randomness and add a command to switch the colour.

This workshop is supposed to help teaching basic physics principle and that would really help with it. The usecase would be as follow:

As I student I would like to

- Set the angle, the power and a colour
- I trigger a throw and I see the trajectory in the same colour as the block
- I change the angle, the colour and the power
- I make a new throw, and now I see two trajectories, in two different colours
- I can compare the trajectories and make deductions
- I can make more throws or clean the trajectories using a command

Does that make sense?

**Comment by AdityaGupta1** [comment]
Yeah, makes sense

I will add a color argument to the command and have an internal color -> block HashMap

There is already support for multiple trajectories, so this shouldn't be too hard, as long as I can figure out how to color the particles

**Comment by AdityaGupta1** [comment]
I've made a new custom particle that can be colored (and doesn't move downwards like the original one); I will work on the HashMap soon

**Comment by AdityaGupta1** [comment]
Added eight colors:

**Red:** redstone
**Green:** emerald
**Blue:** lapis lazuli
**Cyan:** diamond
**Yellow:** gold
**Purple:** portal
**White:** iron
**Black:** obsidian

Catapult command is now `/catapult <angle> <power> <color>`
