### ISSUE TITLE
Make power selector more sensitive

### ISSUE THREAD

**Issue by cesartl** [AdityaGupta1/minecraft-catapult#16]
Currently there is a big difference between power 2 and power 3. With a low angle (e.g 15) power 2 won't even leave the catapult, but power 3 will send it far away.

We should make the power control a bit more sensitive. For example Power 20 could be equivalent to the current power 3

**Comment by AdityaGupta1** [comment]
The power now works on a log base 3 scale, so power 27 now is power 3 before.
