### ISSUE TITLE
Make riding block explode on impact

### ISSUE THREAD

**Issue by cesartl** [AdityaGupta1/minecraft-catapult#19]
It would be cool if the blocks could explode on impact.

I have a world with multiple island and I'd love to be able to destroy the other island from far away :D

**Comment by AdityaGupta1** [comment]
I'll add a command to toggle this behavior.

**Comment by AdityaGupta1** [comment]
Seems that this won't work because I am using the `remote` world for spawning entities, and explosions can only occur in the non-`remote` world. If I use the non-`remote` world, the cows will get off the falling blocks and the falling blocks will disappear after a fraction of a second.
